
LinkModifier = LinkModifier or {}
function LinkModifier:Start()
    LinkLuaModifier("modifier_movespeed_x4", "libraries/modifiers/modifier_movespeed_x4", LUA_MODIFIER_MOTION_NONE)
	LinkLuaModifier("modifier_movespeed_x2", "libraries/modifiers/modifier_movespeed_x2", LUA_MODIFIER_MOTION_NONE)
	LinkLuaModifier("modifier_antiblock", "libraries/modifiers/modifier_antiblock", LUA_MODIFIER_MOTION_NONE) 
	LinkLuaModifier("modifier_innate_controller", "libraries/modifiers/modifier_innate_controller", LUA_MODIFIER_MOTION_NONE)
    LinkLuaModifier("modifier_antibase", "libraries/modifiers/modifier_antibase", LUA_MODIFIER_MOTION_NONE)
	LinkLuaModifier("modifier_building", "libraries/modifiers/modifier_building", LUA_MODIFIER_MOTION_NONE)
	LinkLuaModifier("modifier_disconnected", "libraries/modifiers/modifier_disconnected", LUA_MODIFIER_MOTION_NONE)
	LinkLuaModifier("modifier_disconnected_unit", "libraries/modifiers/modifier_disconnected_unit", LUA_MODIFIER_MOTION_NONE)
	LinkLuaModifier("modifier_out_of_world", "libraries/modifiers/modifier_out_of_world", LUA_MODIFIER_MOTION_NONE)
	LinkLuaModifier("modifier_builder_hidden", "libraries/modifiers/modifier_builder_hidden", LUA_MODIFIER_MOTION_NONE)
	LinkLuaModifier("modifier_repairing", "libraries/modifiers/repair_modifiers", LUA_MODIFIER_MOTION_NONE)
	LinkLuaModifier("modifier_builder_repairing", "libraries/modifiers/repair_modifiers", LUA_MODIFIER_MOTION_NONE)
	LinkLuaModifier("modifier_minimap", "libraries/modifiers/modifier_minimap", LUA_MODIFIER_MOTION_NONE)
	LinkLuaModifier("modifier_tree_cut", "libraries/modifiers/modifier_tree_cut", LUA_MODIFIER_MOTION_NONE)
	LinkLuaModifier("modifier_poison", "libraries/modifiers/modifier_poison", LUA_MODIFIER_MOTION_NONE)
	LinkLuaModifier("modifier_all_vision", "libraries/modifiers/modifier_all_vision", LUA_MODIFIER_MOTION_NONE)
	LinkLuaModifier("modifier_buff_glyph_counter", "modifiers/modifier_buff_glyph_counter", LUA_MODIFIER_MOTION_NONE)
	LinkLuaModifier("modifier_antifeed", "modifiers/modifier_antifeed", LUA_MODIFIER_MOTION_NONE)
	LinkLuaModifier("modifier_boots_2", "modifiers/modifier_boots_2", LUA_MODIFIER_MOTION_NONE)
	LinkLuaModifier("modifier_kill_time", "modifiers/modifier_kill_time", LUA_MODIFIER_MOTION_NONE)
	LinkLuaModifier("modifier_death_armor", "libraries/modifiers/modifier_death_armor", LUA_MODIFIER_MOTION_NONE)
	LinkLuaModifier("modifier_death_mana", "libraries/modifiers/modifier_death_mana", LUA_MODIFIER_MOTION_NONE)
	LinkLuaModifier("modifier_cosmetic_pet", "modifiers/modifier_cosmetic_pet", LUA_MODIFIER_MOTION_NONE )
	LinkLuaModifier("modifier_custom_armor", "libraries/modifiers/modifier_custom_armor", LUA_MODIFIER_MOTION_NONE)
	LinkLuaModifier("modifier_generic_invisibility", "modifiers/modifier_generic_invisibility", LUA_MODIFIER_MOTION_NONE)
	LinkLuaModifier("part_mod", "modifiers/parts/part_mod", LUA_MODIFIER_MOTION_NONE )
	LinkLuaModifier("modifier_skill_troll_hp", "modifiers/modifier_skill_troll_hp", LUA_MODIFIER_MOTION_NONE )
	LinkLuaModifier("modifier_skill_troll_armor", "modifiers/modifier_skill_troll_armor", LUA_MODIFIER_MOTION_NONE )
	LinkLuaModifier("modifier_skill_troll_attack_speed", "modifiers/modifier_skill_troll_attack_speed", LUA_MODIFIER_MOTION_NONE )
	LinkLuaModifier("modifier_skill_troll_crit", "modifiers/modifier_skill_troll_crit", LUA_MODIFIER_MOTION_NONE )
	LinkLuaModifier("modifier_skill_troll_damage", "modifiers/modifier_skill_troll_damage", LUA_MODIFIER_MOTION_NONE )
	LinkLuaModifier("modifier_skill_troll_hp_reg", "modifiers/modifier_skill_troll_hp_reg", LUA_MODIFIER_MOTION_NONE )
	LinkLuaModifier("modifier_skill_troll_lifesteal", "modifiers/modifier_skill_troll_lifesteal", LUA_MODIFIER_MOTION_NONE )
	LinkLuaModifier("modifier_skill_troll_ms", "modifiers/modifier_skill_troll_ms", LUA_MODIFIER_MOTION_NONE )
	LinkLuaModifier("modifier_skill_troll_bkb", "modifiers/modifier_skill_troll_bkb", LUA_MODIFIER_MOTION_NONE )
	LinkLuaModifier("modifier_skill_troll_cd_reduce", "modifiers/modifier_skill_troll_cd_reduce", LUA_MODIFIER_MOTION_NONE )

	LinkLuaModifier("modifier_spell_test", "modifiers/modifier_spell_test", LUA_MODIFIER_MOTION_NONE )
	LinkLuaModifier("modifier_spell_test_2", "modifiers/modifier_spell_test_2", LUA_MODIFIER_MOTION_NONE )
	LinkLuaModifier("modifier_spell_test_3", "modifiers/modifier_spell_test_3", LUA_MODIFIER_MOTION_NONE )
	LinkLuaModifier("modifier_spell_test_4", "modifiers/modifier_spell_test_4", LUA_MODIFIER_MOTION_NONE )
	LinkLuaModifier("modifier_spell_test_5", "modifiers/modifier_spell_test_5", LUA_MODIFIER_MOTION_NONE )

	LinkLuaModifier("modifier_troll_spell_ms", "modifiers/modifier_troll_spell_ms", LUA_MODIFIER_MOTION_NONE )
	LinkLuaModifier("modifier_troll_spell_gold_hit", "modifiers/modifier_troll_spell_gold_hit", LUA_MODIFIER_MOTION_NONE )
	LinkLuaModifier("modifier_troll_spell_hp_reg", "modifiers/modifier_troll_spell_hp_reg", LUA_MODIFIER_MOTION_NONE )
	LinkLuaModifier("modifier_troll_spell_limit_gold", "modifiers/modifier_troll_spell_limit_gold", LUA_MODIFIER_MOTION_NONE )
	LinkLuaModifier("modifier_troll_spell_cd_reduce", "modifiers/modifier_troll_spell_cd_reduce", LUA_MODIFIER_MOTION_NONE )
	LinkLuaModifier("modifier_troll_spell_block_damage", "modifiers/modifier_troll_spell_block_damage", LUA_MODIFIER_MOTION_NONE )
	LinkLuaModifier("modifier_troll_spell_armor", "modifiers/modifier_troll_spell_armor", LUA_MODIFIER_MOTION_NONE )
	LinkLuaModifier("modifier_troll_spell_vision", "modifiers/modifier_troll_spell_vision", LUA_MODIFIER_MOTION_NONE )
	LinkLuaModifier("modifier_troll_spell_magic_resist", "modifiers/modifier_troll_spell_magic_resist", LUA_MODIFIER_MOTION_NONE )
	LinkLuaModifier("modifier_troll_spell_status_resist", "modifiers/modifier_troll_spell_status_resist", LUA_MODIFIER_MOTION_NONE )
	LinkLuaModifier("modifier_troll_spell_silence_target", "modifiers/modifier_troll_spell_silence_target", LUA_MODIFIER_MOTION_NONE )
	LinkLuaModifier("modifier_troll_spell_silence_area", "modifiers/modifier_troll_spell_silence_area", LUA_MODIFIER_MOTION_NONE )
	LinkLuaModifier("modifier_troll_spell_stun_target", "modifiers/modifier_troll_spell_stun_target", LUA_MODIFIER_MOTION_NONE )
	LinkLuaModifier("modifier_troll_spell_haste", "modifiers/modifier_troll_spell_haste", LUA_MODIFIER_MOTION_NONE )
	LinkLuaModifier("modifier_troll_spell_ward", "modifiers/modifier_troll_spell_ward", LUA_MODIFIER_MOTION_NONE )
	LinkLuaModifier("modifier_troll_spell_bkb", "modifiers/modifier_troll_spell_bkb", LUA_MODIFIER_MOTION_NONE )
	LinkLuaModifier("modifier_troll_spell_slow_target", "modifiers/modifier_troll_spell_slow_target", LUA_MODIFIER_MOTION_NONE )
	LinkLuaModifier("modifier_troll_spell_slow_area", "modifiers/modifier_troll_spell_slow_area", LUA_MODIFIER_MOTION_NONE )
	LinkLuaModifier("modifier_troll_spell_invis", "modifiers/modifier_troll_spell_invis", LUA_MODIFIER_MOTION_NONE )
	LinkLuaModifier("modifier_troll_spell_evasion", "modifiers/modifier_troll_spell_evasion", LUA_MODIFIER_MOTION_NONE )
	LinkLuaModifier("modifier_troll_spell_atkspeed", "modifiers/modifier_troll_spell_atkspeed", LUA_MODIFIER_MOTION_NONE )
	LinkLuaModifier("modifier_troll_spell_wolf", "modifiers/modifier_troll_spell_wolf", LUA_MODIFIER_MOTION_NONE )
	LinkLuaModifier("modifier_troll_spell_reveal", "modifiers/modifier_troll_spell_reveal", LUA_MODIFIER_MOTION_NONE )
	LinkLuaModifier("modifier_troll_spell_night_buff", "modifiers/modifier_troll_spell_night_buff", LUA_MODIFIER_MOTION_NONE ) 
	LinkLuaModifier("modifier_troll_spell_ms_max", "modifiers/modifier_troll_spell_ms_max", LUA_MODIFIER_MOTION_NONE)
	LinkLuaModifier("modifier_troll_spell_gold_wisp", "modifiers/modifier_troll_spell_gold_wisp", LUA_MODIFIER_MOTION_NONE)
	LinkLuaModifier("modifier_elf_spell_ms", "modifiers/modifier_elf_spell_ms", LUA_MODIFIER_MOTION_NONE)
	LinkLuaModifier("modifier_elf_spell_gold", "modifiers/modifier_elf_spell_gold", LUA_MODIFIER_MOTION_NONE)
	LinkLuaModifier("modifier_elf_spell_lumber", "modifiers/modifier_elf_spell_lumber", LUA_MODIFIER_MOTION_NONE )	
	LinkLuaModifier("modifier_elf_spell_cd_reduce", "modifiers/modifier_elf_spell_cd_reduce", LUA_MODIFIER_MOTION_NONE )	
	LinkLuaModifier("modifier_elf_spell_cd_worker", "modifiers/modifier_elf_spell_cd_worker", LUA_MODIFIER_MOTION_NONE )	
	LinkLuaModifier("modifier_worker_spell_cd_reduce", "modifiers/modifier_worker_spell_cd_reduce", LUA_MODIFIER_MOTION_NONE )	
	LinkLuaModifier("modifier_elf_spell_armor_wall", "modifiers/modifier_elf_spell_armor_wall", LUA_MODIFIER_MOTION_NONE )	
	LinkLuaModifier("modifier_wall_spell_armor", "modifiers/modifier_wall_spell_armor", LUA_MODIFIER_MOTION_NONE )	
	LinkLuaModifier("modifier_elf_spell_tower_damage", "modifiers/modifier_elf_spell_tower_damage", LUA_MODIFIER_MOTION_NONE )	
	LinkLuaModifier("modifier_tower_spell_dmg", "modifiers/modifier_tower_spell_dmg", LUA_MODIFIER_MOTION_NONE )	
	LinkLuaModifier("modifier_elf_spell_limit_gold", "modifiers/modifier_elf_spell_limit_gold", LUA_MODIFIER_MOTION_NONE )	
	LinkLuaModifier("modifier_elf_spell_limit_lumber", "modifiers/modifier_elf_spell_limit_lumber", LUA_MODIFIER_MOTION_NONE )	
	LinkLuaModifier("modifier_elf_spell_true", "modifiers/modifier_elf_spell_true", LUA_MODIFIER_MOTION_NONE )	
	LinkLuaModifier("modifier_elf_spell_tower_range", "modifiers/modifier_elf_spell_tower_range", LUA_MODIFIER_MOTION_NONE )	
	LinkLuaModifier("modifier_tower_spell_range", "modifiers/modifier_tower_spell_range", LUA_MODIFIER_MOTION_NONE )	
	LinkLuaModifier("modifier_elf_spell_blink", "modifiers/modifier_elf_spell_blink", LUA_MODIFIER_MOTION_NONE )	
	LinkLuaModifier("modifier_elf_spell_damage_gold", "modifiers/modifier_elf_spell_damage_gold", LUA_MODIFIER_MOTION_NONE )	
	LinkLuaModifier("modifier_elf_spell_invis", "modifiers/modifier_elf_spell_invis", LUA_MODIFIER_MOTION_NONE )	
	LinkLuaModifier("modifier_elf_spell_smoke", "modifiers/modifier_elf_spell_smoke", LUA_MODIFIER_MOTION_NONE )	
	LinkLuaModifier("modifier_elf_spell_haste", "modifiers/modifier_elf_spell_haste", LUA_MODIFIER_MOTION_NONE )	
	LinkLuaModifier("modifier_elf_spell_evasion", "modifiers/modifier_elf_spell_evasion", LUA_MODIFIER_MOTION_NONE )	
	LinkLuaModifier("modifier_elf_spell_target_buff", "modifiers/modifier_elf_spell_target_buff", LUA_MODIFIER_MOTION_NONE )	
	LinkLuaModifier("modifier_elf_spell_target_damage", "modifiers/modifier_elf_spell_target_damage", LUA_MODIFIER_MOTION_NONE )	
	LinkLuaModifier("modifier_elf_spell_teleport", "modifiers/modifier_elf_spell_teleport", LUA_MODIFIER_MOTION_NONE )	
	LinkLuaModifier("modifier_elf_spell_stun_target", "modifiers/modifier_elf_spell_stun_target", LUA_MODIFIER_MOTION_NONE )	
	LinkLuaModifier("modifier_elf_spell_heal", "modifiers/modifier_elf_spell_heal", LUA_MODIFIER_MOTION_NONE )	
	LinkLuaModifier("modifier_elf_spell_reveal", "modifiers/modifier_elf_spell_reveal", LUA_MODIFIER_MOTION_NONE )	


	--LinkLuaModifier("modifier_elf_spell_", "modifiers/modifier_elf_spell_", LUA_MODIFIER_MOTION_NONE )	
	--LinkLuaModifier("modifier_elf_spell_", "modifiers/modifier_elf_spell_", LUA_MODIFIER_MOTION_NONE )	
	--LinkLuaModifier("modifier_elf_spell_", "modifiers/modifier_elf_spell_", LUA_MODIFIER_MOTION_NONE )	

	
	
	--[[
	Сломано
	LinkLuaModifier("modifier_elf_spell_", "modifiers/modifier_elf_spell_", LUA_MODIFIER_MOTION_NONE )	

	LinkLuaModifier("modifier_troll_spell_", "modifiers/modifier_troll_spell_", LUA_MODIFIER_MOTION_NONE )
]]
	
end
