Wearables = {}
Wearables.wolfModels = {
    ["620"] = { model = "models/items/lycan/ultimate/blood_moon_hunter_shapeshift_form/blood_moon_hunter_shapeshift_form.vmdl", scale = 1 },
    ["621"] = { model = "models/items/lycan/ultimate/sirius_curse/sirius_curse.vmdl", scale = 1 },
    ["622"] = { model = "models/items/lycan/ultimate/ambry_true_form/ambry_true_form.vmdl", scale = 1 },
    ["623"] = { model = "models/items/lycan/ultimate/thegreatcalamityti4/thegreatcalamityti4.vmdl", scale = 1 },
    ["624"] = { model = "models/items/lycan/ultimate/hunter_kings_trueform/hunter_kings_trueform.vmdl", scale = 1 },
    ["625"] = { model = "models/items/lycan/ultimate/alpha_trueform9/alpha_trueform9.vmdl", scale = 1 },
    ["626"] = { model = "models/items/lycan/ultimate/_ascension_of_the_hallowed_beast_form/_ascension_of_the_hallowed_beast_form.vmdl", scale = 1 },
    ["627"] = { model = "models/items/lycan/ultimate/frostivus2018_lycan_savage_beast_form/frostivus2018_lycan_savage_beast_form.vmdl", scale = 1 },
    ["628"] = { model = "models/items/lycan/ultimate/2018_lycan_shapeshift/2018_lycan_shapeshift.vmdl", scale = 1 },
    ["629"] = { model = "models/items/lycan/ultimate/mutant_exorcist_form/mutant_exorcist_form.vmdl", scale = 1 },
    ["630"] = { model = "models/items/lycan/ultimate/_werewolf_samurai_wolf_form_v1/_werewolf_samurai_wolf_form_v1.vmdl", scale = 1 },
    ["631"] = { model = "models/items/lycan/ultimate/watchdog_lycan_true_form/watchdog_lycan_true_form.vmdl", scale = 1 },
}

Wearables.bearModels = {
    ["673"] = { model = "models/items/lone_druid/true_form/dark_wood_true_form/dark_wood_true_form.vmdl", scale = 0.7 },
    ["674"] = { model = "models/items/lone_druid/true_form/elemental_curse_set_elemental_curse_true_form/elemental_curse_set_elemental_curse_true_form.vmdl", scale = 0.7 },
    ["675"] = { model = "models/items/lone_druid/true_form/form_of_the_atniw/form_of_the_atniw.vmdl", scale = 0.7 },
    ["676"] = { model = "models/items/lone_druid/true_form/frostivus2018_lone_druid_inuit_trueform/frostivus2018_lone_druid_inuit_trueform.vmdl", scale = 0.7 },
    ["677"] = { model = "models/items/lone_druid/true_form/iron_claw_true_form/iron_claw_true_form.vmdl", scale = 0.7 },
    ["678"] = { model = "models/items/lone_druid/true_form/ld_enslaved_wanderer_ability_2/ld_enslaved_wanderer_ability_2.vmdl", scale = 0.7 },
    ["679"] = { model = "models/items/lone_druid/true_form/rabid_black_bear/rabid_black_bear.vmdl", scale = 0.7 },
    ["680"] = { model = "models/items/lone_druid/true_form/tarzan_and_kingkong_trueform/tarzan_and_kingkong_trueform.vmdl", scale = 0.7 },
    ["681"] = { model = "models/items/lone_druid/true_form/wizened_bear/wizened_bear.vmdl", scale = 0.7 },
    ["682"] = { model = "models/items/lone_druid/true_form/wolf_hunter_true_form/wolf_hunter_true_form.vmdl", scale = 0.7 },
}

Wearables.elfModels = {
    ["601"] = { model = "models/creeps/lane_creeps/creep_radiant_melee/radiant_melee_mega.vmdl", scale = 1 },
    ["602"] = { model = "models/creeps/lane_creeps/creep_radiant_melee/crystal_radiant_melee.vmdl", scale = 1 },
    ["603"] = { model = "models/creeps/lane_creeps/creep_radiant_melee/radiant_melee_crystal.vmdl", scale = 1 },
    ["604"] = { model = "models/creeps/lane_creeps/creep_radiant_melee/radiant_melee_mega_crystal.vmdl", scale = 1 },
    ["605"] = { model = "models/creeps/lane_creeps/creep_radiant_ranged/radiant_ranged.vmdl", scale = 1 },
    ["606"] = { model = "models/creeps/lane_creeps/creep_radiant_ranged/radiant_ranged_mega.vmdl", scale = 1 },
    ["607"] = { model = "models/creeps/lane_creeps/creep_radiant_ranged/crystal_radiant_ranged.vmdl", scale = 1 },
    ["608"] = { model = "models/creeps/lane_creeps/creep_radiant_ranged/radiant_ranged_crystal.vmdl", scale = 1 },
    ["609"] = { model = "models/creeps/lane_creeps/creep_radiant_ranged/radiant_ranged_mega_crystal.vmdl", scale = 1 },
    ["610"] = { model = "models/creeps/lane_creeps/creep_bad_ranged/lane_dire_ranged.vmdl", scale = 1 },
    ["611"] = { model = "models/creeps/lane_creeps/creep_bad_ranged/lane_dire_ranged_mega.vmdl", scale = 1 },
    ["612"] = { model = "models/creeps/lane_creeps/creep_bad_melee/creep_bad_melee_mega.vmdl", scale = 1 },
    ["613"] = { model = "models/creeps/lane_creeps/creep_bad_ranged/creep_bad_ranged_crystal.vmdl", scale = 1 },
    ["614"] = { model = "models/creeps/lane_creeps/creep_bad_ranged/creep_bad_ranged_mega_crystal.vmdl", scale = 1 },
    ["615"] = { model = "models/creeps/lane_creeps/creep_bad_melee/creep_bad_melee.vmdl", scale = 1 },
    ["616"] = { model = "models/creeps/lane_creeps/creep_bad_melee/creep_bad_melee_crystal.vmdl", scale = 1 },
    ["617"] = { model = "models/creeps/lane_creeps/creep_bad_melee/creep_bad_melee_mega_crystal.vmdl", scale = 1 },
    ["618"] = { model = "models/items/wraith_king/wk_ti8_creep/wk_ti8_creep_golden.vmdl", scale = 1 },
    ["619"] = { model = "models/items/wraith_king/wk_ti8_creep/wk_ti8_creep_crimson.vmdl", scale = 1 },
    ["635"] = { model = "models/creeps/lane_creeps/creep_2021_radiant/creep_2021_radiant_flagbearer_melee.vmdl", scale = 1 },
    ["636"] = { model = "models/creeps/lane_creeps/creep_2021_radiant/creep_2021_radiant_flagbearer_melee_mega.vmdl", scale = 1 },
    ["637"] = { model = "models/creeps/lane_creeps/creep_2021_radiant/creep_2021_radiant_ranged.vmdl", scale = 1 },
    ["638"] = { model = "models/creeps/lane_creeps/creep_2021_radiant/creep_2021_radiant_ranged_mega.vmdl", scale = 1 },
    ["639"] = { model = "models/creeps/lane_creeps/creep_2021_dire/creep_2021_dire_melee.vmdl", scale = 1 },
    ["640"] = { model = "models/creeps/lane_creeps/creep_2021_dire/creep_2021_dire_melee_mega.vmdl", scale = 1 },
    ["641"] = { model = "models/creeps/lane_creeps/creep_2021_dire/creep_2021_dire_ranged.vmdl", scale = 1 },
    ["642"] = { model = "models/creeps/lane_creeps/creep_2021_dire/creep_2021_dire_ranged_mega.vmdl", scale = 1 },
    ["643"] = { model = "models/items/wraith_king/arcana/wk_arcana_skeleton.vmdl", scale = 1.2 },
    ["644"] = { model = "models/creeps/lane_creeps/ti9_chameleon_radiant/ti9_chameleon_radiant_flagbearer_melee.vmdl", scale = 1 },
    ["645"] = { model = "models/creeps/lane_creeps/ti9_chameleon_radiant/ti9_chameleon_radiant_flagbearer_melee_mega.vmdl", scale = 1 },
    ["646"] = { model = "models/creeps/lane_creeps/ti9_chameleon_radiant/ti9_chameleon_radiant_ranged.vmdl", scale = 1 },
    ["647"] = { model = "models/creeps/lane_creeps/ti9_chameleon_radiant/ti9_chameleon_radiant_ranged_mega.vmdl", scale = 1 },
    ["648"] = { model = "models/creeps/lane_creeps/ti9_crocodilian_dire/ti9_crocodilian_dire_flagbearer_melee.vmdl", scale = 1 },
    ["649"] = { model = "models/creeps/lane_creeps/ti9_crocodilian_dire/ti9_crocodilian_dire_flagbearer_melee_mega.vmdl", scale = 1 },
    ["650"] = { model = "models/creeps/lane_creeps/ti9_crocodilian_dire/ti9_crocodilian_dire_ranged.vmdl", scale = 1 },
    ["651"] = { model = "models/creeps/lane_creeps/ti9_crocodilian_dire/ti9_crocodilian_dire_ranged_mega.vmdl", scale = 1 },
    ["652"] = { model = "models/creeps/pine_cone/pine_cone.vmdl", scale = 1 },
    ["653"] = { model = "models/heroes/furion/treant.vmdl", scale = 1 },
    ["654"] = { model = "models/items/furion/treant_flower_1.vmdl", scale = 1 },
    ["655"] = { model = "models/items/furion/treant_stump.vmdl", scale = 1 },
    ["656"] = { model = "models/items/furion/treant/abyssal_prophet_abyssal_prophet_treant/abyssal_prophet_abyssal_prophet_treant.vmdl", scale = 1 },
    ["657"] = { model = "models/items/furion/treant/allfather_of_nature_treant/allfather_of_nature_treant.vmdl", scale = 1 },
    ["658"] = { model = "models/items/furion/treant/defender_of_the_jungle_lakad_coconut/defender_of_the_jungle_lakad_coconut.vmdl", scale = 1 },
    ["659"] = { model = "models/items/furion/treant/eternalseasons_treant/eternalseasons_treant.vmdl", scale = 1 },
    ["660"] = { model = "models/items/furion/treant/father_treant/father_treant.vmdl", scale = 1 },
    ["661"] = { model = "models/items/furion/treant/fungal_lord_shroomthing/fungal_lord_shroomthing.vmdl", scale = 1 },
    ["662"] = { model = "models/items/furion/treant/furion_treant_nelum_red/furion_treant_nelum_red.vmdl", scale = 1 },
    ["663"] = { model = "models/items/furion/treant/hallowed_horde/hallowed_horde.vmdl", scale = 1 },
    ["664"] = { model = "models/items/furion/treant/np_cute_cactus_treant/np_cute_cactus_treant.vmdl", scale = 1 },
    ["665"] = { model = "models/items/furion/treant/np_desert_traveller_treant/np_desert_traveller_treant.vmdl", scale = 1 },
    ["666"] = { model = "models/creeps/mega_greevil/mega_greevil.vmdl", scale = 1.7 },
    ["667"] = { model = "models/items/furion/treant/primeval_treant/primeval_treant.vmdl", scale = 1 },
    ["668"] = { model = "models/items/furion/treant/ravenous_woodfang/ravenous_woodfang.vmdl", scale = 1 },
    ["669"] = { model = "models/items/furion/treant/shroomling_treant/shroomling_treant.vmdl", scale = 1 },
    ["670"] = { model = "models/items/furion/treant/supreme_gardener_treants/supreme_gardener_treants.vmdl", scale = 1 },
    ["671"] = { model = "models/items/furion/treant/the_ancient_guardian_the_ancient_treants/the_ancient_guardian_the_ancient_treants.vmdl", scale = 1 },
    ["672"] = { model = "models/items/furion/treant/treant_cis/treant_cis.vmdl", scale = 1 },
    ["683"] = { model = "models/heroes/invoker/forge_spirit.vmdl", scale = 1 },
    ["684"] = { model = "models/items/invoker/forge_spirit/arsenal_magus_forged_spirit/arsenal_magus_forged_spirit.vmdl", scale = 1 },
    ["685"] = { model = "models/items/invoker/forge_spirit/cadenza_spirit/cadenza_spirit.vmdl", scale = 1 },
    ["686"] = { model = "models/items/invoker/forge_spirit/covenant_of_the_depths_deep_forged/covenant_of_the_depths_deep_forged.vmdl", scale = 1 },
    ["687"] = { model = "models/items/invoker/forge_spirit/dark_sorcerer_forge_spirit/dark_sorcerer_forge_spirit.vmdl", scale = 1 },
    ["688"] = { model = "models/items/invoker/forge_spirit/esl_relics_forge_spirit/esl_relics_forge_spirit.vmdl", scale = 1 },
    ["689"] = { model = "models/items/invoker/forge_spirit/esl_relics_forge_spirit/esl_relics_forge_spirit_dpc.vmdl", scale = 1 },
    ["690"] = { model = "models/items/invoker/forge_spirit/frostivus2018_invoker_keeper_of_magic_spirit/frostivus2018_invoker_keeper_of_magic_spirit.vmdl", scale = 1 },
    ["691"] = { model = "models/items/invoker/forge_spirit/grievous_ingots/grievous_ingots.vmdl", scale = 1 },
    ["692"] = { model = "models/items/invoker/forge_spirit/iceforged_spirit/iceforged_spirit.vmdl", scale = 1 },
    ["693"] = { model = "models/items/invoker/forge_spirit/infernus/infernus.vmdl", scale = 1 },
    ["694"] = { model = "models/items/invoker/forge_spirit/nightlord_crypt_sentinel/nightlord_crypt_sentinel.vmdl", scale = 1 },
    ["695"] = { model = "models/items/invoker/forge_spirit/sempiternal_revelations_forged_spirits/sempiternal_revelations_forged_spirits.vmdl", scale = 1.2 },
    ["696"] = { model = "models/items/invoker/forge_spirit/steampowered_magic_forge_spirit/steampowered_magic_forge_spirit.vmdl", scale = 1 },
    ["697"] = { model = "models/items/invoker/forge_spirit/ti8_invoker_prism_forge_spirit/ti8_invoker_prism_forge_spirit.vmdl", scale = 1 },
    ["698"] = { model = "models/items/wraith_king/frostivus_wraith_king/frostivus_wraith_king_skeleton.vmdl", scale = 1.2 },
}
local p
local p12 = nil
Wearables.skinConfigs = {}
Wearables.skinConfigs = {
    ["1001"] = { -- Venomancer Hydra
        attachments = {
            "models/items/venomancer/venomancer_hydra_switch_color_arms/venomancer_hydra_switch_color_arms.vmdl",
            "models/items/venomancer/venomancer_hydra_switch_color_shoulder/venomancer_hydra_switch_color_shoulder.vmdl",
            "models/items/venomancer/venomancer_hydra_switch_color_head/venomancer_hydra_switch_color_head.vmdl",
            "models/items/venomancer/venomancer_hydra_switch_color_tail/venomancer_hydra_switch_color_tail.vmdl",
        },
    },
    ["1002"] = { -- King Viper
        attachments = {
            "models/items/viper/king_viper_head/king_viper_head.vmdl",
            "models/items/viper/king_viper_back/king_viper_back.vmdl",
            "models/items/viper/king_viper_tail/viper_king_viper_tail.vmdl",
        },
    },
    ["1003"] = { -- Drow Immortal
        attachments = {
            "models/items/drow/drow_ti9_immortal_weapon/drow_ti9_immortal_weapon.vmdl",
            "models/items/drow/mask_of_madness/mask_of_madness.vmdl",
            "models/items/drow/frostfeather_huntress_shoulder/frostfeather_huntress_shoulder.vmdl",
            "models/items/drow/frostfeather_huntress_misc/frostfeather_huntress_misc.vmdl",
            "models/items/drow/ti6_immortal_cape/mesh/drow_ti6_immortal_cape.vmdl",
            "models/items/drow/frostfeather_huntress_arms/frostfeather_huntress_arms.vmdl",
            "models/items/drow/frostfeather_huntress_legs/frostfeather_huntress_legs.vmdl",
        },
        particles = {{ path = "particles/econ/items/drow/drow_ti6_gold/drow_ti6_ambient_gold.vpcf", cp = 1, attachType = PATTACH_POINT_FOLLOW, attachName = "follow_origin" }},
    },
    ["1004"] = { -- Windrunner Arcana
        attachments = {
            "models/items/windrunner/windrunner_arcana/wr_arcana_cape.vmdl",
            "models/items/windrunner/windrunner_arcana/wr_arcana_quiver.vmdl",
            "models/items/windrunner/windrunner_arcana/wr_arcana_shoulder.vmdl",
            "models/items/windrunner/windrunner_arcana/wr_arcana_head.vmdl",
            "models/items/windrunner/windrunner_arcana/wr_arcana_weapon.vmdl",
        },
    },
    ["1005"] = { -- Ancient Apparition
        attachments = {
            "models/items/ancient_apparition/ancient_apparition_frozen_evil_head/ancient_apparition_frozen_evil_head.vmdl",
            "models/items/ancient_apparition/ancient_apparition_frozen_evil_arms/ancient_apparition_frozen_evil_arms.vmdl",
            "models/items/ancient_apparition/ancient_apparition_frozen_evil_shoulder/ancient_apparition_frozen_evil_shoulder.vmdl",
            "models/items/ancient_apparition/ancient_apparition_frozen_evil_tail/ancient_apparition_frozen_evil_tail.vmdl",
        },
    },
    ["1006"] = { -- Vengeful Spirit
        attachments = {
            "models/items/vengefulspirit/fallenprincess_head/fallenprincess_head.vmdl",
            "models/items/vengefulspirit/fallenprincess_legs/fallenprincess_legs.vmdl",
            "models/items/vengefulspirit/fallenprincess_weapon/fallenprincess_weapon.vmdl",
            "models/items/vengefulspirit/vs_ti8_immortal_shoulder/vs_ti8_immortal_shoulder.vmdl",
        },
        particles = {{ path = "particles/econ/items/vengeful/vs_ti8_immortal_shoulder/vs_ti8_immortal_shoulder_crimson_ambient.vpcf", cp = 1, attachType = PATTACH_POINT_FOLLOW, attachName = "follow_origin" }},
    },
    ["1007"] = { -- Shadow Fiend Arcana
        attachments = {
            "models/items/shadow_fiend/arms_deso/arms_deso.vmdl",
            "models/heroes/shadow_fiend/head_arcana.vmdl",
            "models/items/nevermore/sf_souls_tyrant_shoulder/sf_souls_tyrant_shoulder.vmdl",
        },
    },
    ["1008"] = { -- Nevermore Ferrum
        attachments = {
            "models/items/nevermore/ferrum_chiroptera_head/ferrum_chiroptera_head.vmdl",
            "models/items/nevermore/ferrum_chiroptera_shoulder/ferrum_chiroptera_shoulder.vmdl",
            "models/items/nevermore/ferrum_chiroptera_arms/ferrum_chiroptera_arms.vmdl",
        },
        particles = {
            { path = "particles/units/heroes/hero_nevermore/shadow_fiend_ambient_eyes.vpcf", cp = 1, attachType = PATTACH_POINT_FOLLOW, attachName = "follow_origin" },
            { path = "particles/econ/items/shadow_fiend/sf_ferrum/shadow_fiend_ferrum_head_ambient.vpcf", cp = 2, attachType = PATTACH_POINT_FOLLOW, attachName = "follow_origin" },
            { path = "particles/econ/items/shadow_fiend/sf_ferrum/shadow_fiend_ferrum_shoulder_ambient.vpcf", cp = 3, attachType = PATTACH_POINT_FOLLOW, attachName = "attach_hook" },
        },
    },
    ["1009"] = { -- Templar Assassin Archives
        attachments = {
            "models/items/lanaya/raiment_of_the_violet_archives_shoulder/raiment_of_the_violet_archives_shoulder.vmdl",
            "models/items/lanaya/raiment_of_the_violet_archives_armor/raiment_of_the_violet_archives_armor.vmdl",
            "models/items/lanaya/raiment_of_the_violet_archives_head_hood/raiment_of_the_violet_archives_head_hood.vmdl",
        },
    },
    ["1010"] = { -- Luna Ti7
        attachments = {
            "models/items/luna/luna_ti7_set_head/luna_ti7_set_head.vmdl",
            "models/items/luna/luna_ti7_set_mount/luna_ti7_set_mount.vmdl",
            "models/items/luna/luna_ti7_set_shoulder/luna_ti7_set_shoulder.vmdl",
            "models/items/luna/luna_ti7_set_weapon/luna_ti7_set_weapon.vmdl",
            "models/items/luna/luna_ti7_set_offhand/luna_ti7_set_offhand.vmdl",
        },
    },
    ["1011"] = { -- Medusa Ti10
        attachments = {
            "models/items/medusa/dotaplus_medusa_weapon/dotaplus_medusa_weapon.vmdl",
            "models/items/medusa/daughters_of_hydrophiinae/daughters_of_hydrophiinae.vmdl",
            "models/items/medusa/medusa_ti10_immortal_tail/medusa_ti10_immortal_tail.vmdl",
            "models/items/medusa/dotaplas_medusa_head/dotaplas_medusa_head.vmdl",
            "models/items/medusa/dotaplus_medusa_arms/dotaplus_medusa_arms.vmdl",
        },
    },
    ["1012"] = { -- Enigma Tentacular
        attachments = {
            "models/items/enigma/tentacular_conqueror_armor/tentacular_conqueror_armor.vmdl",
            "models/items/enigma/tentacular_conqueror_arms/tentacular_conqueror_arms.vmdl",
            "models/items/enigma/tentacular_conqueror_head/tentacular_conqueror_head.vmdl",
        },
    },
    ["1013"] = { -- Sniper Witch Hunter
        attachments = {
            "models/items/sniper/witch_hunter_set_weapon/witch_hunter_set_weapon.vmdl",
            "models/items/sniper/witch_hunter_set_shoulder/witch_hunter_set_shoulder.vmdl",
            "models/items/sniper/witch_hunter_set_arms/witch_hunter_set_arms.vmdl",
            "models/items/sniper/witch_hunter_set_head/witch_hunter_set_head.vmdl",
            "models/items/sniper/witch_hunter_set_back/witch_hunter_set_back.vmdl",
        },
    },
    ["1014"] = { updateModel = { model = "models/items/wards/frozen_formation/frozen_formation.vmdl", scale = 1 } },
    ["1015"] = { updateModel = { model = "models/items/wards/sylph_ward/sylph_ward.vmdl", scale = 1 } },
    ["1016"] = { updateModel = { model = "models/items/wards/watcher_below_ward/watcher_below_ward.vmdl", scale = 1 } },
    ["1017"] = { updateModel = { model = "models/items/wards/megagreevil_ward/megagreevil_ward.vmdl", scale = 1 } },
    ["1018"] = { updateModel = { model = "models/items/wards/dire_ward_eye/dire_ward_eye.vmdl", scale = 1 } },
    ["1019"] = { updateModel = { model = "models/items/wards/chinese_ward/chinese_ward.vmdl", scale = 1 } },
    ["1020"] = { updateModel = { model = "models/items/wards/stonebound_ward/stonebound_ward.vmdl", scale = 1 } },
    ["1021"] = { updateModel = { model = "models/items/wards/monty_ward/monty_ward.vmdl", scale = 1 } },
    ["1022"] = { updateModel = { model = "models/items/wards/gazing_idol_ward/gazing_idol_ward.vmdl", scale = 1 } },
    ["1023"] = { updateModel = { model = "models/items/courier/throe/throe_flying.vmdl", scale = 1 } },
    ["1024"] = { updateModel = { model = "models/items/courier/shagbark/shagbark_flying.vmdl", scale = 1 } },
    ["1025"] = { updateModel = { model = "models/items/courier/courier_mvp_redkita/courier_mvp_redkita_flying.vmdl", scale = 1 } },
    ["1026"] = { updateModel = { model = "models/items/courier/defense4_dire/defense4_dire_flying.vmdl", scale = 1 } },
    ["1027"] = { updateModel = { model = "models/items/courier/mlg_wraith_courier/mlg_wraith_courier.vmdl", scale = 1 } },
    ["1028"] = { updateModel = { model = "models/items/courier/mei_nei_rabbit/mei_nei_rabbit_flying.vmdl", scale = 1 } },
    ["1029"] = { updateModel = { model = "models/items/courier/mango_the_courier/mango_the_courier_flying.vmdl", scale = 1 } },
    ["1030"] = { updateModel = { model = "models/items/courier/blazing_hatchling_the_fortune_bringer_courier/blazing_hatchling_the_fortune_bringer_courier_flying.vmdl", scale = 1 } },
    ["1031"] = { updateModel = { model = "models/items/courier/bookwyrm/bookwyrm_flying.vmdl", scale = 1 } },
    ["1032"] = {
        attachments = {
            "models/items/drow/wandering_ranger_head/wandering_ranger_head.vmdl",
            "models/items/drow/wandering_ranger_back/wandering_ranger_back.vmdl",
            "models/items/drow/wandering_ranger_arms/wandering_ranger_arms.vmdl",
            "models/items/drow/wandering_ranger_weapon/wandering_ranger_weapon.vmdl",
            "models/items/drow/wandering_ranger_shoulder/wandering_ranger_shoulder.vmdl",
            "models/items/drow/wandering_ranger_misc/wandering_ranger_misc.vmdl",
            "models/items/drow/wandering_ranger_legs/wandering_ranger_legs.vmdl",
        },
        custom = function(bld)
            local w = SpawnEntityFromTableSynchronous("prop_dynamic", { model = "models/items/drow/wandering_ranger_weapon/wandering_ranger_weapon.vmdl" })
            w:FollowEntity(bld, true)
            local p1 = ParticleManager:CreateParticle("particles/econ/items/drow/drow_2022_cc/drow_2022_cc_weapon.vpcf", PATTACH_ABSORIGIN_FOLLOW, w)
            ParticleManager:SetParticleControlEnt(p1, 1, bld, PATTACH_POINT_FOLLOW, nil, bld:GetOrigin(), true)
            local p2 = ParticleManager:CreateParticle("particles/econ/items/drow/drow_2022_cc/drow_2022_cc_quiver.vpcf", PATTACH_POINT_FOLLOW, bld)
            ParticleManager:SetParticleControlEnt(p2, 2, bld, PATTACH_POINT_FOLLOW, "follow_origin", bld:GetAbsOrigin(), true)
        end,
    },
    ["1033"] = {
        attachments = {
            "models/items/windrunner/ti6_windranger_back/ti6_windranger_back.vmdl",
            "models/items/windrunner/ti6_windranger_head/ti6_windranger_head.vmdl",
            "models/items/windrunner/ti6_windranger_offhand/ti6_windranger_offhand.vmdl",
            "models/items/windrunner/ti6_windranger_shoulder/ti6_windranger_shoulder.vmdl",
            "models/items/windrunner/ti6_windranger_weapon/ti6_windranger_weapon.vmdl",
        },
    },
    ["1034"] = {
        attachments = {
            "models.items/hoodwink/hood_2021_blossom_weapon/hood_2021_blossom_weapon.vmdl",
            "models/items/hoodwink/hood_2021_blossom_armor/hood_2021_blossom_armor.vmdl",
            "models/items/hoodwink/hood_2021_blossom_tail/hood_2021_blossom_tail.vmdl",
            "models/items/hoodwink/hood_2021_blossom_back/hood_2021_blossom_back.vmdl",
        },
    },
    ["1035"] = {
        attachments = {
            "models/items/clinkz/degraded_soul_hunter_weapon/degraded_soul_hunter_weapon.vmdl",
            "models/items/clinkz/degraded_soul_hunter_shoulder/degraded_soul_hunter_shoulder.vmdl",
            "models/items/clinkz/degraded_soul_hunter_head/degraded_soul_hunter_head.vmdl",
            "models/items/clinkz/degraded_soul_hunter_gloves/degraded_soul_hunter_gloves.vmdl",
            "models/items/clinkz/degraded_soul_hunter_back/degraded_soul_hunter_back.vmdl",
        },
    },
    ["1036"] = { updateModel = { model = "models/flag_2.vmdl", scale = 0.5 } },
    ["1037"] = { updateModel = { model = "models/items/wards/arcticwatchtower/arcticwatchtower.vmdl", scale = 1 } },
    ["1038"] = { updateModel = { model = "models/items/wards/atlas_burden_ward/atlas_burden_ward.vmdl", scale = 1 } },
    ["1039"] = { updateModel = { model = "models/items/wards/augurys_guardian/augurys_guardian.vmdl", scale = 1 } },
    ["1040"] = { updateModel = { model = "models/items/wards/chicken_hut_ward/chicken_hut_ward.vmdl", scale = 1 } },
    ["1041"] = { updateModel = { model = "models/items/wards/bane_ward/bane_ward.vmdl", scale = 1 } },
    ["1042"] = { updateModel = { model = "models/items/wards/echo_bat_ward/echo_bat_ward.vmdl", scale = 1 } },
    ["1043"] = { updateModel = { model = "models/items/wards/enchantedvision_ward/enchantedvision_ward.vmdl", scale = 1 } },
    ["1044"] = { updateModel = { model = "models/items/wards/esl_one_jagged_vision/esl_one_jagged_vision.vmdl", scale = 1 } },
    ["1045"] = { updateModel = { model = "models/items/wards/esl_wardchest_radling_ward/esl_wardchest_radling_ward.vmdl", scale = 1 } },
    ["1046"] = { updateModel = { model = "models/items/wards/esl_wardchest_franglerfish/esl_wardchest_franglerfish.vmdl", scale = 1 } },
    ["1047"] = { updateModel = { model = "models/items/wards/esl_wardchest_jungleworm/esl_wardchest_jungleworm.vmdl", scale = 1 } },
    ["1048"] = { updateModel = { model = "models/items/wards/esl_wardchest_toadstool/esl_wardchest_toadstool.vmdl", scale = 1 } },
    ["1049"] = { updateModel = { model = "models/items/wards/eye_of_avernus_ward/eye_of_avernus_ward.vmdl", scale = 1 } },
    ["1050"] = { updateModel = { model = "models/items/wards/ti8_snail_ward/ti8_snail_ward.vmdl", scale = 1 } },
    ["1051"] = { updateModel = { model = "models/items/wards/frostivus_2023_ward/frostivus_2023_ward.vmdl", scale = 1 } },
    ["1052"] = { updateModel = { model = "models/items/wards/jakiro_pyrexae_ward/jakiro_pyrexae_ward.vmdl", scale = 1 } },
    ["1053"] = { updateModel = { model = "models/items/wards/hand_2021_ward/hand_2021_ward.vmdl", scale = 1 } },
    ["1054"] = { updateModel = { model = "models/items/wards/knightstatue_ward/knightstatue_ward.vmdl", scale = 1 } },
    ["1055"] = { updateModel = { model = "models/items/wards/lich_black_pool_watcher/lich_black_pool_watcher.vmdl", scale = 1 } },
    ["1056"] = { updateModel = { model = "models/items/wards	revtel_jester_obs/revtel_jester_obs.vmdl", scale = 1 } },
    ["1057"] = { updateModel = { model = "models/items/wards	the_monkey_sentinel/the_monkey_sentinel.vmdl", scale = 1 } },
    ["1058"] = { updateModel = { model = "models/items/wards/warding_guise/warding_guise.vmdl", scale = 1 } },
}